# Generated by Django 3.2.25 on 2024-06-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20240525_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_in_wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
